apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpanginx
spec:
  scaleTargetRef:
    apiVersion: app/v1
    kind: Deployment
    name: python-webapp
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50