apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpanginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1       # ✅ fixed
    kind: Deployment
    name: python-webapp       # ✅ ensure this matches your deployment name
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 25
